name: Flask CI

on:   
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build . -t flask-app:ci

      - name: Run Container
        run: |
          docker run -d --name flask-app-container -p 5000:5000  flask-app:ci

      - name: Wait for Container to be Ready
        run: sleep 10

      - name: View Container Logs
        run: docker logs flask-app-container

      - name: Run pytest
        run: |
          docker exec flask-app-container sh -c "PYTHONPATH=/app pytest -v /app/tests/"

